Semantic-mockup
js-tasks-ru/htmlcss-20210409_alexandr8 pull request #2
Opened 2021-04-22 18:26 UTC by av-starodub

2021-04-22 18:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-23 10:38 UTC, GSemikozov requested changes

2021-04-23 10:38 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/style.css
> +    background: #6b6d5562;
достаточно без лишних переусложнений использовать стандартный способ задания кода цвета через 16-тиричную систему

2021-04-23 10:46 UTC, merged

2021-04-23 10:50 UTC, av-starodub commented on 02-dz0/01-semantic-mockup/style.css
> +    background: #6b6d5562;
Понял, спасибо.